server:
  port: 5000
spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    web:
      path: /web/**
      serviceId: web
    consumer:
      path: /consumer/**
      serviceId: consumer