server:
  port: 8080

spring:
  application:
    name: web
  # freemarker 配置
  freemarker:
      allow-request-override: false
      # 缓存是否开启 true开启
      cache: false
      # 配合cache使用 cache true 这个需要写时间
      settings.template_update_delay: 0
      check-template-location: true
      charset: UTF-8
      content-type: text/html
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
      request-context-attribute: ctx
  # jdbc
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/za_edu_cloud_platform_auth?characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
      username: root
      password: 666666
  # 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

eureka:
  instance:
    # true 使用IP注册
    preferIpAddress: true
    # 心跳间隔
    lease-renewal-interval-in-seconds: 3
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    # fegin fallback
    enabled: true

mybatis:
  typeAliasesPackage: com.ssxu.entity
  mapperLocations: classpath:mapper/**/*.xml
  # 当返回值为空时 只是值为空 而不是把键直接去掉
  configuration:
    call-setters-on-nulls: true

htmlpath: http://localhost:8080


